# LocalLink installer (PowerShell, Windows)
#
# Usage:
#   irm https://raw.githubusercontent.com/m7md2323/LocalLink/main/install.ps1 | iex
#
# Or with options:
#   $env:LOCAL_LINK_REPO = "https://github.com/you/LocalLink.git"
#   irm https://raw.githubusercontent.com/m7md2323/LocalLink/main/install.ps1 | iex
#
# Requires: PowerShell 5.1+ (ships with Windows 10+) and Python 3.10+.

$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

$Repo = if ($env:LOCAL_LINK_REPO) { $env:LOCAL_LINK_REPO } else { "https://github.com/m7md2323/LocalLink.git" }
$Branch = if ($env:LOCAL_LINK_BRANCH) { $env:LOCAL_LINK_BRANCH } else { "main" }
$InstallDir = if ($env:LOCAL_LINK_INSTALL_DIR) { $env:LOCAL_LINK_INSTALL_DIR } else { Join-Path $env:USERPROFILE ".locallink" }
$Force = $env:LOCAL_LINK_FORCE -eq "1" -or $env:LOCAL_LINK_YES -eq "1" -or $args -contains "-y" -or $args -contains "--yes"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

function Log($msg)  { Write-Host "[locallink] $msg" -ForegroundColor Cyan }
function Warn($msg) { Write-Host "[locallink] $msg" -ForegroundColor Yellow }
function Fail($msg) { Write-Host "[locallink] $msg" -ForegroundColor Red; exit 1 }

function Find-Python {
    $candidates = @("python3.12", "python3.11", "python3.10", "python", "py")
    foreach ($cmd in $candidates) {
        $path = Get-Command $cmd -ErrorAction SilentlyContinue
        if ($path) {
            $versionOutput = & $path --version 2>&1
            if ($versionOutput -match "Python (\d+)\.(\d+)") {
                $major = [int]$Matches[1]
                $minor = [int]$Matches[2]
                if ($major -gt 3 -or ($major -eq 3 -and $minor -ge 10)) {
                    return $path.Source
                }
            }
        }
    }
    Fail "Python 3.10+ not found. Install from https://www.python.org/downloads/ (tick 'Add to PATH')."
}

function Get-ScriptsDir {
    # pip installs console scripts to <venv>\Scripts on Windows.
    # That directory is already on PATH when the venv is activated,
    # but for a system-wide install we want it permanently.
    # We use the same Scripts dir and tell the user to add it to PATH
    # if it isn't already.
    return (Join-Path $InstallDir "venv\Scripts")
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

Log "LocalLink installer (Windows)"
Log "Install dir: $InstallDir"
Log "Repo:        $Repo"

$Python = Find-Python
Log "Using Python: $Python (& $Python --version 2>&1)"

# Reinstall if force flag set, else prompt.
if (Test-Path $InstallDir) {
    if ($Force) {
        Warn "Reinstalling into $InstallDir..."
        Remove-Item -Recurse -Force $InstallDir
    } else {
        $confirm = Read-Host "Install directory already exists. Remove and reinstall? [y/N]"
        if ($confirm -match "^[Yy]$") {
            Remove-Item -Recurse -Force $InstallDir
        } else {
            Log "Aborted."
            exit 0
        }
    }
}

# Clone or copy.
if (Test-Path $Repo -PathType Container) {
    Log "Installing from local checkout: $Repo"
    Copy-Item -Recurse -Force $Repo $InstallDir
} else {
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        Fail "git is required to clone the repository. Install git or set LOCAL_LINK_REPO to a local directory."
    }
    Log "Cloning repository: $Repo (branch $Branch)"
    git clone --depth 1 --branch $Branch $Repo $InstallDir
}

# Virtual environment.
Log "Creating Python virtual environment..."
& $Python -m venv (Join-Path $InstallDir "venv")

$VenvPython = Join-Path $InstallDir "venv\Scripts\python.exe"
$VenvPip = Join-Path $InstallDir "venv\Scripts\pip.exe"

Log "Installing dependencies..."
& $VenvPython -m pip install --upgrade pip --quiet
& $VenvPython -m pip install -r (Join-Path $InstallDir "requirements.txt") --quiet

# Create a .bat launcher in the Scripts dir (already on PATH when venv is active).
$ScriptsDir = Get-ScriptsDir
$Launcher = Join-Path $ScriptsDir "locallink.bat"
Log "Creating launcher at $Launcher"
@"
@echo off
REM LocalLink launcher — generated by install.ps1
cd /d "$InstallDir"
"$VenvPython" "$InstallDir\run.py" %*
"@ | Set-Content -Path $Launcher -Encoding ASCII

Log ""
Log "Installation complete!"
Log ""
Log "To run, you need the Scripts dir on your PATH. Either:"
Log "  1. Activate the venv:  $InstallDir\venv\Scripts\Activate.ps1"
Log "     then run:  locallink"
Log "  2. Or add to PATH permanently (PowerShell, current user):"
Log "     [Environment]::SetEnvironmentVariable('Path', $ScriptsDir + ';' + [Environment]::GetEnvironmentVariable('Path','User'), 'User')"
Log "     then open a new terminal and run:  locallink"
Log ""
Log "Configuration:"
Log "  Copy-Item $InstallDir\.env.example $InstallDir\.env"
Log "  notepad $InstallDir\.env"
